name: vbf_ditau
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - seaborn 
  - pandas
  - h5py
  - scikit-learn
  - ipykernel
  - pip
  - pip:
      - polars
      - ptflops
      - hydra-core
      - rich
      - loguru
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio
      - torchinfo
      - lightning==2.5.*
      - ignite